import tkinter
root = tkinter.Tk()
#タイトル表示
root.title("画像表示したい")
#サイズ固定
root.resizable(False,False)
canvas = tkinter.Canvas(root,width=1000,height=700)
canvas.pack()
gazou0 = tkinter.PhotoImage(file="C:\\Users\\namimatsuren\Documents\GitHub\geekcamp_pytramp\gazou_display\Splitted-Image-0-0.png")
canvas.create_image(100,500,image=gazou0)
gazou1 = tkinter.PhotoImage(file="C:\\Users\\namimatsuren\Documents\GitHub\geekcamp_pytramp\gazou_display\Splitted-Image-1-0.png")
canvas.create_image(150,500,image=gazou1)
gazou2 = tkinter.PhotoImage(file="C:\\Users\\namimatsuren\Documents\GitHub\geekcamp_pytramp\gazou_display\Splitted-Image-2-0.png")
canvas.create_image(200,500,image=gazou2)
gazou3 = tkinter.PhotoImage(file="C:\\Users\\namimatsuren\Documents\GitHub\geekcamp_pytramp\gazou_display\Splitted-Image-3-0.png")
canvas.create_image(250,500,image=gazou3)
gazou4 = tkinter.PhotoImage(file="C:\\Users\\namimatsuren\Documents\GitHub\geekcamp_pytramp\gazou_display\Splitted-Image-4-0.png")
canvas.create_image(300,500,image=gazou4)
gazou5 = tkinter.PhotoImage(file="C:\\Users\\namimatsuren\Documents\GitHub\geekcamp_pytramp\gazou_display\Splitted-Image-5-0.png")
canvas.create_image(350,500,image=gazou5)
gazou6 = tkinter.PhotoImage(file="C:\\Users\\namimatsuren\Documents\GitHub\geekcamp_pytramp\gazou_display\Splitted-Image-6-0.png")
canvas.create_image(400,500,image=gazou6)
gazou7 = tkinter.PhotoImage(file="C:\\Users\\namimatsuren\Documents\GitHub\geekcamp_pytramp\gazou_display\Splitted-Image-7-0.png")
canvas.create_image(450,500,image=gazou7)
gazou8 = tkinter.PhotoImage(file="C:\\Users\\namimatsuren\Documents\GitHub\geekcamp_pytramp\gazou_display\Splitted-Image-8-0.png")
canvas.create_image(500,500,image=gazou8)
gazou9 = tkinter.PhotoImage(file="C:\\Users\\namimatsuren\Documents\GitHub\geekcamp_pytramp\gazou_display\Splitted-Image-9-0.png")
canvas.create_image(550,500,image=gazou9)
gazou10 = tkinter.PhotoImage(file="C:\\Users\\namimatsuren\Documents\GitHub\geekcamp_pytramp\gazou_display\Splitted-Image-10-0.png")
canvas.create_image(600,500,image=gazou10)
gazou11 = tkinter.PhotoImage(file="C:\\Users\\namimatsuren\Documents\GitHub\geekcamp_pytramp\gazou_display\Splitted-Image-11-0.png")
canvas.create_image(650,500,image=gazou11)
gazou12 = tkinter.PhotoImage(file="C:\\Users\\namimatsuren\Documents\GitHub\geekcamp_pytramp\gazou_display\Splitted-Image-12-0.png")
canvas.create_image(700,500,image=gazou12)

root.title("画像表示したい")
root.geometry("1000x800")

root.mainloop()
